# Generated by Django 6.0.3 on 2026-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='client_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
