# Generated by Django 4.2.29 on 2026-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_maintenanceschedule_client_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost for this service type', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='max_daily_assignments',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of this service type a technician can be assigned per day'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='procedures',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of procedure steps, e.g. [{'step': 1, 'title': '...', 'description': '...'}]"),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='required_equipment',
            field=models.JSONField(blank=True, default=list, help_text="List of required tools/equipment, e.g. [{'name': 'Drill', 'quantity': 1}]"),
        ),
    ]
