# Generated by Django 6.0.3 on 2026-05-03 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_add_servicetype_cost_limits_procedures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['status', 'created_at'], name='services_af_status_1919bc_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['assigned_to', 'status'], name='services_af_assigne_12a36b_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['client', 'status'], name='services_af_client__fda154_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['due_date', 'status'], name='services_af_due_dat_d6d3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['service_type', 'forecast_period', 'forecast_date'], name='services_de_service_276f44_idx'),
        ),
        migrations.AddIndex(
            model_name='demandforecast',
            index=models.Index(fields=['forecast_date'], name='services_de_forecas_9149d8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['status', 'next_due_date'], name='services_ma_status_1756e8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['client', 'status'], name='services_ma_client__4aa047_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['service_type', 'status'], name='services_ma_service_746c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceanalytics',
            index=models.Index(fields=['service_type', '-date'], name='services_se_service_777872_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatushistory',
            index=models.Index(fields=['ticket', '-timestamp'], name='services_se_ticket__2577de_idx'),
        ),
        migrations.AddIndex(
            model_name='servicestatushistory',
            index=models.Index(fields=['status', '-timestamp'], name='services_se_status_29b933_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'status'], name='services_se_supervi_76c7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['supervisor_id', 'created_at'], name='services_se_supervi_45028b_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['completed_date'], name='services_se_complet_5a669e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['scheduled_date', 'scheduled_time'], name='services_se_schedul_9cc62e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicetrend',
            index=models.Index(fields=['service_type', 'trend_type', 'period_start', 'period_end'], name='services_se_service_81b7db_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocationhistory',
            index=models.Index(fields=['technician', '-timestamp'], name='services_te_technic_582174_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianlocationhistory',
            index=models.Index(fields=['-timestamp'], name='services_te_timesta_4b38af_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianperformance',
            index=models.Index(fields=['technician', '-date'], name='services_te_technic_dfe938_idx'),
        ),
    ]
