# Generated by Django 6.0.3 on 2026-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_aftersalescase_services_af_status_1919bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionchecklist',
            name='checklist_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='procedure_source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='required_equipment_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspectionchecklist',
            name='service_type_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
