# Generated by Django 6.0.3 on 2026-05-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_admin_owned_management_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='services.servicerequest')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='services.servicetype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('request', 'service_type'), name='unique_service_type_per_request')],
            },
        ),
    ]
