# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='messages', to='services.serviceticket'),
        ),
        migrations.AddField(
            model_name='message',
            name='group_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='room_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], default='direct', max_length=20),
        ),
    ]
