# Generated by Django 4.2.29 on 2026-05-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0011_alter_user_options_user_users_user_role_f59a08_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='The primary key of the changed record')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Type of change: create, update, or delete', max_length=20)),
                ('field_name', models.CharField(blank=True, default='', help_text='The specific field that changed (empty for create/delete)', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Value before the change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='Value after the change', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('summary', models.CharField(blank=True, default='', help_text='Human-readable summary of the change', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, help_text='The user who made this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(help_text='The model type that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='users_chang_content_46a98d_idx'), models.Index(fields=['changed_by', 'changed_at'], name='users_chang_changed_45d8fb_idx'), models.Index(fields=['action', 'changed_at'], name='users_chang_action_95889f_idx')],
            },
        ),
    ]
