# Generated by Django 6.0.3 on 2026-05-10 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('corporate', 'Corporate')], default='individual', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('sms', 'SMS')], default='email', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='FollowUpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance'), ('warranty', 'Warranty'), ('complaint', 'Complaint Resolution')], default='general', max_length=20)),
                ('max_case_load', models.PositiveSmallIntegerField(default=50)),
                ('current_case_load', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Follow-Up Profile',
                'verbose_name_plural': 'Follow-Up Profiles',
            },
        ),
        migrations.CreateModel(
            name='ManagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_scope', models.CharField(choices=[('service_follow_up', 'Service Follow-Up'), ('task_management', 'Task Management'), ('operations', 'Operations Management'), ('general', 'General Administration')], default='general', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Management Profile',
                'verbose_name_plural': 'Management Profiles',
            },
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('field_service', 'Field Service'), ('maintenance', 'Maintenance'), ('installation', 'Installation'), ('repair', 'Repair')], default='field_service', max_length=20)),
                ('max_technicians', models.PositiveSmallIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supervisor Profile',
                'verbose_name_plural': 'Supervisor Profiles',
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('preferred_work_areas', models.JSONField(blank=True, default=list)),
                ('max_daily_assignments', models.PositiveSmallIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technician Profile',
                'verbose_name_plural': 'Technician Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='usercapabilitygrant',
            options={'ordering': ['user', 'capability_code'], 'verbose_name': 'User Capability Grant', 'verbose_name_plural': 'User Capability Grants'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_f59a08_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('follow_up', 'Follow-Up Specialist'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followupprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managementprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin_scope',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_location_update',
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['client_type'], name='users_clien_client__254b09_idx'),
        ),
        migrations.AddIndex(
            model_name='followupprofile',
            index=models.Index(fields=['specialization'], name='users_follo_special_9b47f0_idx'),
        ),
        migrations.AddIndex(
            model_name='supervisorprofile',
            index=models.Index(fields=['department'], name='users_super_departm_93729c_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['is_available'], name='users_techn_is_avai_264a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['skill_level'], name='users_techn_skill_l_4eb0b1_idx'),
        ),
    ]
