# Generated by Django 5.2.13 on 2026-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number (11 digits, format: +63 9XX XXX XXXX)', max_length=20, null=True),
        ),
    ]
