# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('superadmin', 'Superadmin'),
                    ('admin', 'Admin'),
                    ('follow_up', 'Service Follow-Up'),
                    ('supervisor', 'Supervisor'),
                    ('technician', 'Technician'),
                    ('client', 'Client'),
                ],
                default='client',
                max_length=20,
            ),
        ),
    ]
